// <auto-generated />
using System;
using InventoryService.Worker.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryService.Worker.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260720183946_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryService.Worker.Idempotency.ProcessedOrder", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderId");

                    b.ToTable("ProcessedOrders", (string)null);
                });

            modelBuilder.Entity("InventoryService.Worker.Stock.StockItem", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.ToTable("StockItems", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = "APPLE-1",
                            AvailableQuantity = 100
                        },
                        new
                        {
                            ProductId = "BANANA-1",
                            AvailableQuantity = 50
                        },
                        new
                        {
                            ProductId = "MANGO-1",
                            AvailableQuantity = 3
                        },
                        new
                        {
                            ProductId = "DURIAN-1",
                            AvailableQuantity = 999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
